(define (my-equal? a b)
  (cond ((and (null? a) (null? b)) #t)
        ((and (pair? a) (pair? b))
         (and (my-equal? (car a) (car b))
              (my-equal? (cdr a) (cdr b))))
        ((eq? (pair? a) (pair? b) #f)
         (eq? a b))
        (else #f)))

(my-equal? 1 1)
(my-equal? 1 2)
(my-equal? '() '())
(my-equal? '() 'abc)
(my-equal? '(1 2 3) '(1 2 3))
(my-equal? '(1 2 3) '(1 9 3))
(my-equal? '(1 (a b c) 3) '(1 (a b c) 3))
(my-equal? '(1 (a b c) 3) '(1 (a b c e) 3))