(define (make-from-mag-ang m a)
  (define (dispatch op)
    (cond ((eq? op 'real-part) (* m (cos a)))
          ((eq? op 'imag-part) (* m (sin a)))
          ((eq? op 'magnitude) m)
          ((eq? op 'angle) a)
          (else (error "unknown operation" op))))
  dispatch)

(define (apply-generic op arg) (arg op))

(define c (make-from-mag-ang 4 5))
(apply-generic 'real-part c)
(apply-generic 'imag-part c)
(apply-generic 'magnitude c)
(apply-generic 'angle c)